# Generated by Django 4.0.4 on 2022-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Recipe', models.TextField()),
                ('Price', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
