# Generated by Django 4.0.4 on 2022-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
